---
apiVersion: v1
kind: Service

metadata:
  name: oauth2-proxy
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/component: server

spec:
  selector:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/component: server

  ports:
    - name: http
      port: 8080

...
